CREATE TABLE hotel_bookings (
    id SERIAL PRIMARY KEY,
    hotel VARCHAR(50),
    is_canceled INT,
    lead_time INT,
    arrival_date_year INT,
    arrival_date_month VARCHAR(15),
    arrival_date_week_number INT,
    arrival_date_day_of_month INT,
    stays_in_weekend_nights INT,
    stays_in_week_nights INT,
    adults INT,
    children FLOAT,
    babies INT,
    meal VARCHAR(50),
    country VARCHAR(5),
    market_segment VARCHAR(50),
    distribution_channel VARCHAR(50),
    is_repeated_guest INT,
    previous_cancellations INT,
    previous_bookings_not_canceled INT,
    reserved_room_type VARCHAR(5),
    assigned_room_type VARCHAR(5),
    booking_changes INT,
    deposit_type VARCHAR(50),
    agent FLOAT,
    company FLOAT,
    days_in_waiting_list INT,
    customer_type VARCHAR(50),
    adr FLOAT,
    required_car_parking_spaces INT,
    total_of_special_requests INT,
    reservation_status VARCHAR(50),
    reservation_status_date DATE
);

-- Insert dummy data
INSERT INTO hotel_bookings (
        hotel,
        is_canceled,
        lead_time,
        arrival_date_year,
        arrival_date_month,
        arrival_date_week_number,
        arrival_date_day_of_month,
        stays_in_weekend_nights,
        stays_in_week_nights,
        adults,
        children,
        babies,
        meal,
        country,
        market_segment,
        distribution_channel,
        is_repeated_guest,
        previous_cancellations,
        previous_bookings_not_canceled,
        reserved_room_type,
        assigned_room_type,
        booking_changes,
        deposit_type,
        agent,
        company,
        days_in_waiting_list,
        customer_type,
        adr,
        required_car_parking_spaces,
        total_of_special_requests,
        reservation_status,
        reservation_status_date
    )
VALUES (
        'Resort Hotel',
        0,
        342,
        2024,
        'July',
        27,
        1,
        0,
        0,
        2,
        0,
        0,
        'BB',
        'USA',
        'Direct',
        'Direct',
        0,
        0,
        0,
        'A',
        'A',
        0,
        'No Deposit',
        NULL,
        NULL,
        0,
        'Transient',
        100.0,
        0,
        1,
        'Check-Out',
        '2024-07-01'
    ),
    (
        'City Hotel',
        1,
        120,
        2024,
        'August',
        32,
        15,
        1,
        4,
        2,
        1,
        0,
        'FB',
        'PRT',
        'Online',
        'TA/TO',
        0,
        1,
        2,
        'B',
        'A',
        1,
        'Refundable',
        304,
        NULL,
        15,
        'Contract',
        250.0,
        1,
        2,
        'Canceled',
        '2024-08-15'
    ),
    (
        'Resort Hotel',
        0,
        7,
        2024,
        'July',
        27,
        5,
        0,
        1,
        1,
        0,
        0,
        'HB',
        'FRA',
        'Corporate',
        'Corporate',
        1,
        0,
        5,
        'C',
        'B',
        0,
        'No Deposit',
        NULL,
        234,
        0,
        'Transient',
        150.0,
        0,
        0,
        'Check-Out',
        '2024-07-05'
    ),
    (
        'City Hotel',
        1,
        15,
        2024,
        'September',
        36,
        18,
        2,
        5,
        3,
        1,
        0,
        'HB',
        'GBR',
        'Groups',
        'Direct',
        1,
        0,
        0,
        'D',
        'B',
        0,
        'No Deposit',
        240,
        125,
        10,
        'Group',
        300.5,
        0,
        2,
        'No-Show',
        '2024-09-18'
    ),
    (
        'Resort Hotel',
        0,
        250,
        2023,
        'June',
        23,
        10,
        2,
        3,
        2,
        0,
        1,
        'BB',
        'BRA',
        'Corporate',
        'Corporate',
        0,
        0,
        1,
        'A',
        'A',
        0,
        'No Deposit',
        NULL,
        NULL,
        0,
        'Transient',
        500.0,
        1,
        0,
        'Check-Out',
        '2023-06-10'
    ),
    (
        'City Hotel',
        1,
        80,
        2023,
        'May',
        20,
        8,
        1,
        6,
        3,
        1,
        0,
        'FB',
        'ESP',
        'TA/TO',
        'TA/TO',
        0,
        2,
        0,
        'B',
        'C',
        2,
        'Refundable',
        320,
        NULL,
        0,
        'Transient',
        225.0,
        0,
        1,
        'Canceled',
        '2023-05-08'
    ),
    (
        'Resort Hotel',
        0,
        500,
        2022,
        'October',
        40,
        20,
        0,
        4,
        1,
        0,
        0,
        'HB',
        'DEU',
        'Direct',
        'Direct',
        1,
        0,
        2,
        'C',
        'C',
        0,
        'No Deposit',
        NULL,
        NULL,
        0,
        'Transient',
        180.0,
        0,
        2,
        'Check-Out',
        '2022-10-20'
    ),
    (
        'City Hotel',
        1,
        45,
        2022,
        'November',
        45,
        22,
        1,
        7,
        2,
        0,
        1,
        'BB',
        'NLD',
        'Online',
        'TA/TO',
        0,
        1,
        1,
        'A',
        'B',
        0,
        'No Deposit',
        123,
        45,
        12,
        'Transient',
        135.0,
        1,
        3,
        'Canceled',
        '2022-11-22'
    ),
    (
        'Resort Hotel',
        0,
        30,
        2021,
        'December',
        50,
        25,
        3,
        2,
        2,
        1,
        0,
        'HB',
        'ITA',
        'Groups',
        'Direct',
        0,
        0,
        1,
        'D',
        'D',
        0,
        'No Deposit',
        NULL,
        NULL,
        0,
        'Transient',
        400.0,
        1,
        0,
        'Check-Out',
        '2021-12-25'
    ),
    (
        'City Hotel',
        1,
        10,
        2021,
        'October',
        43,
        15,
        0,
        5,
        3,
        2,
        0,
        'FB',
        'AUS',
        'Corporate',
        'Corporate',
        1,
        2,
        3,
        'E',
        'E',
        1,
        'Refundable',
        435,
        NULL,
        20,
        'Contract',
        650.0,
        2,
        4,
        'Canceled',
        '2021-10-15'
    );